name: Another bug report
description: For 1.4
title: 'Bug'
labels: ["bug", "triage"]
projects: ["Cetabet-1234/Lab04"]
assignees:
  - Cetabet-1234
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. <email@example.com>
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: request
    attributes:
      label: Type of request?
      description: select the type of your request
      options:
        - New Feature
        - Bug Fix 
      default: 0
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What is the OS which you want to suggest?
      multiple: true
      options:
        - Windows
        - Linux
        - MacOS
        - Other

  - type: textarea
    id: logs
    attributes:
      label: What are the detail of your suggestion?
      description: Explain what do you want
      render: shell
      value: "Feature deatil!"
    validations:
      required: true